owner: Happynico7504
repo: MastodonUptimeStatus

sites:
  - name: Mastodon by Nico Christmann
    url: https://mastodon.nicochristmann.net
    port: 443
    check: "curl"
    ipv6: true

status-website:
  baseUrl: /MastodonUptimeStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mastodon by Nico Christmann Server Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
